import { mkdir, rm, cp, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'dist');
await rm(output, { recursive: true, force: true });
await mkdir(output);
for (const path of ['index.html', 'admin.html', 'src']) await cp(resolve(root, path), resolve(output, path), { recursive: true });
await cp(resolve(root, 'public/assets'), resolve(output, 'assets'), { recursive: true });
for (const path of ['index.html', 'src/main.js', 'src/style.css', 'assets/floral-watercolor.png']) await stat(resolve(output, path));
console.log('Build frontend selesai: dist/. Jalankan npm run preview dengan backend Node.js untuk admin dan undangan terbit.');
